# DataFlux Configuration File

mode: safe

debug: true

emitters: 100000
flush_batch_size: 1000
flush_interval_sec: 1
retry_probability: 0.05
time_jitter_sec: 0.1

sinks:
  mock:
    type: mock
  kafka:
    type: kafka
    kafka:
      bootstrap_servers: "kafka:29092"  # Using internal Docker network address
      topic: "dataflux-events"
      acks: "all"
      max_retries: 3
      retry_backoff_ms: 100

region_sinks:
  default: [kafka, mock]  # Send to both Kafka and mock for testing

regions:
  - name: us-west
    location: San Francisco, CA
  - name: us-east
    location: New York, NY
  - name: us-central
    location: Chicago, IL
  - name: us-south
    location: Austin, TX
  - name: us-northeast
    location: Boston, MA

streams:
  video_logs:
    weight: 0.25
    interval_sec: 0.01
  user_interactions:
    weight: 0.20
    interval_sec: 0.01
  device_telemetry:
    weight: 0.15
    interval_sec: 0.01
  recommendation_feedback:
    weight: 0.15
    interval_sec: 0.01
  training_data:
    weight: 0.15
    interval_sec: 0.2
  model_telemetry:
    weight: 0.10
    interval_sec: 0.01
