version: '3.8'

services:
  dataflux:
    build: .
    ports:
      - "9100:9100"
      - "8000:8000"
    tty: true
    stdin_open: true
    restart: "no"
    volumes:
      - ./mock_data:/app/mock_data
    environment:
      - PYTHONUNBUFFERED=1
    command: ["tail", "-f", "/dev/null"]
    networks:
      - dataflux_network
    depends_on:
      - kafka
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - dataflux_network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_PROCESS_ROLES: broker
      CLUSTER_ID: test-cluster
    networks:
      - dataflux_network

volumes:
  dataflux_logs:
    driver: local

networks:
  dataflux_network:
    driver: bridge