version: '3.8'

services:
  dataflux:
    build: .
    ports:
      - "9100:9100"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - dataflux_logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  dataflux_logs:
    driver: local
