version: '2'

services:
  dataflux:
    build: .
    ports:
      - "9100:9100"
    tty: true
    stdin_open: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  dataflux_logs:
    driver: local
