version: '3.8'

services:
  dataflux:
    build: .
    ports:
      - "9100:9100"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./mock_data:/app/mock_data
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  dataflux_logs:
    driver: local