apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataflux.fullname" . }}
  labels:
    {{- include "dataflux.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dataflux.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dataflux.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            {{- if .Values.persistence.enabled }}
            - name: logs-volume
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "dataflux.fullname" . }}-config
        {{- if .Values.persistence.enabled }}
        - name: logs-volume
          persistentVolumeClaim:
            claimName: {{ include "dataflux.fullname" . }}-logs
        {{- end }} 